name: Call plugin CI

on:
  workflow_dispatch:
    inputs:
      shopware_version:
        description: "Shopware version"
        required: true
        type: string
        default: 'v6.6.7.0'
      php_version:
        description: "PHP version"
        required: false
        type: string
        default: '8.2'

env:
  PLUGIN_NAME: E2eTest
  PLUGIN_URL: github.com/Isengo1989/e2eplugin.git

jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:
      PLUGIN_NAME: ${{ steps.set-vars.outputs.PLUGIN_NAME }}
      PLUGIN_URL: ${{ steps.set-vars.outputs.PLUGIN_URL }}
    steps:
      - id: set-vars
        run: |
          echo "PLUGIN_NAME=${{ env.PLUGIN_NAME }}" >> $GITHUB_ENV
          echo "PLUGIN_URL=${{ env.PLUGIN_URL }}" >> $GITHUB_ENV
          echo "::set-output name=PLUGIN_NAME::${{ env.PLUGIN_NAME }}"
          echo "::set-output name=PLUGIN_URL::${{ env.PLUGIN_URL }}"
  test-plugin:
    needs: vars
    uses: Isengo1989/plugin-ci/.github/workflows/plugin.yml@main
    with:
      plugin_name: ${{ needs.vars.outputs.PLUGIN_NAME }}
      plugin_url: ${{ needs.vars.outputs.PLUGIN_URL }}
      shopware_version: ${{ inputs.shopware_version }}
      php_version: ${{ inputs.php_version }}
    secrets: inherit