name: Call plugin CI

on:
  workflow_call:
    inputs:
      shopware_version:
        description: "Shopware version"
        required: true
        type: string
      php_version:
        description: "PHP version"
        required: false
        type: string

env:
  PLUGIN_NAME: E2eTest
  PLUGIN_URL: github.com/Isengo1989/plugin-ci.git

jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:
      PLUGIN_NAME: ${{ env.PLUGIN_NAME }}
      PLUGIN_URL: ${{ env.PLUGIN_URL }}
    steps:
      - run: echo "Exposing env vars"
  generate-schema:
    uses: Isengo1989/plugin-ci/.github/workflows/plugin.yml@main
    with:
      shopware_version: ${{ inputs.shopware_version }}
      php_version: ${{ inputs.php_version }}
    secrets: inherit