name: Build and Run Shopware 6 with E2ETest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_api_schema:
    name: "Starup shopware and run E2ETest"
    runs-on: ubuntu-latest
    container: "shopware/development:8.3-composer-2"
    env:
      APP_ENV: prod
      DATABASE_URL: mysql://root:root@database:3306/root
      APP_URL: http://localhost:8000
      APP_SECRET: devsecret
      BLUE_GREEN_DEPLOYMENT: 0

    services:
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root

    steps:
      - name: Test
        run: |
          pwd
          echo "done"

      - name: Checkout Shopware
        uses: actions/checkout@v4
        with:
          repository: shopware/shopware
          ref: v6.6.7.0
          fetch-depth: 0

      - name: configure job
        run: |
          git config --global --add safe.directory /__w/e2eplugin/e2eplugin
          export SWTAG=$(git tag | tr '.' ' ' | sort -nr -k2,3 | head -n1 | tr ' ' '.')

      - name: checkout latest release
        run: |
          git config --global --add safe.directory /__w/e2eplugin/e2eplugin
          git checkout $SWTAG

      - name: Install Composer dependencies
        run: |
          composer install
          composer run init:db

      - name: Pull E2ETest content
        run: |
          ./bin/console plugin:refresh
          ./bin/console plugin:install --activate E2ETest
