name: Build and Run Shopware 6 with E2ETest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_api_schema:
    name: "Generate an openapi3 schema for the given api type"
    runs-on: ubuntu-latest
    container: "shopware/development:8.3-composer-2"
    env:
      APP_ENV: prod
      DATABASE_URL: mysql://root:root@database:3306/root
      APP_URL: http://localhost:8000
      APP_SECRET: devsecret
      BLUE_GREEN_DEPLOYMENT: 0
      SCHEMA_NAME: ""
      SCHEMA_FLAGS: ""
      SCHEMA_FILE: ""

    services:
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root

    steps:
      - name: Test
        run: |
          echo "done"

      - name: Checkout Shopware
        uses: actions/checkout@v4
        with:
          repository: shopware/shopware
          ref: v6.6.7.0
          fetch-depth: 0


      - name: Pull E2ETest content
        run: |
